### ISSUE TITLE
Wire up trashcan to RemoveArticleFromList command

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#1878]

**Comment by davidcmoulton** [comment]
Taiko output:

```
 FAIL  feature-test/save-article-to-list.test.ts (23.34 s)
  save-article-to-list
    given the user is logged in
      and the user already has a generic list
        when the user saves an article that isn't in any list
          ✓ the article appears in the user list page (848 ms)
          ✓ the article appears in the generic list page (606 ms)
          ✓ the article is counted in the list card on the user profile page (691 ms)
          ✓ the last updated date in the list card on the user profile page (738 ms)
          ✓ the user's action appears in the Sciety feed (473 ms)
          ✕ the list count of the article card on the search page increases by one (1396 ms)
          ✕ the list count of the article card on the list page it is in increases by one (347 ms)
          ○ skipped the article card on the list page offers a delete button
          ○ skipped the save article button on the article page is replaced with a link to the list
      and the user only has an empty default user list page and not a generic list
        when the user saves an article that isn't in any list
          ✓ the article appears in the user list page (495 ms)
          ✓ the article appears in the generic list page (387 ms)
          ✓ the article card on the list page offers a delete button (443 ms)
          ✓ the article is counted in the list card on the user profile page (464 ms)
          ✓ the last updated date in the list card on the user profile page (453 ms)
          ✓ the user's action appears in the Sciety feed (330 ms)
          ✓ the list count of the article card on the search page increases by one (329 ms)
          ✓ the list count of the article card on the list page it is in increases by one (496 ms)
          ✓ the user now has a generic list page (396 ms)
          ○ skipped the save article button on the article page is replaced with a link to the list

  ● save-article-to-list › given the user is logged in › and the user already has a generic list › when the user saves an article that isn't in any list › the list count of the article card on the search page increases by one

    expect(received).toContain(expected) // indexOf

    Expected substring: "Appears in 1 list"
    Received string:    "The unique ORF8 protein from SARS-CoV-2 binds to human dendritic cells and induces a hyper-inflammatory cytokine storm
    Hamdorf MImhof TBailey-Elkin BBetz JTheobald SJSimonis ACristanziano VDGieselmann LDewald FLehmann CAugustin MKlein FAlcazar MAARongisch RFabri MRybniker JGoebel HStetefeld JBrachvogel BCursiefen CKoch MBock F
    This article has
    0 evaluationsAppears in 2 listsLatest version Jun 6, 2022"

      88 |           await goto(articleSearchResultsPage);
      89 |           const cardText = await $('.article-card').text();
    > 90 |           expect(cardText).toContain('Appears in 1 list');
         |                            ^
      91 |         });
      92 |
      93 |         it('the list count of the article card on the list page it is in increases by one', async () => {

      at Object.<anonymous> (feature-test/save-article-to-list.test.ts:90:28)

  ● save-article-to-list › given the user is logged in › and the user already has a generic list › when the user saves an article that isn't in any list › the list count of the article card on the list page it is in increases by one

    expect(received).toContain(expected) // indexOf

    Expected substring: "Appears in 1 list"
    Received string:    "Functional peroxisomes are required for heat shock-induced hormesis in Caenorhabditis elegans
    Marina MusaIra MilosevicNuno RaimundoAnita Krisko
    This article has
    0 evaluationsAppears in 2 listsLatest version Jun 6, 2022"

      94 |           await goto(genericListPage);
      95 |           const cardText = await $('.article-card').text();
    > 96 |           expect(cardText).toContain('Appears in 1 list');
         |                            ^
      97 |         });
      98 |
      99 |         it.skip('the save article button on the article page is replaced with a link to the list', async () => {

      at Object.<anonymous> (feature-test/save-article-to-list.test.ts:96:28)

Test Suites: 1 failed, 1 skipped, 12 passed, 13 of 16 total
Tests:       2 failed, 4 skipped, 5 todo, 31 passed, 42 total
Snapshots:   0 total
Time:        24.024 s, estimated 37 s
Ran all test suites.
make: *** [taiko] Error 1

```
