### ISSUE TITLE
Mitigate update data-studio breakage

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#2149]

**Comment by davidcmoulton** [comment]
```
➜ make update-datastudio
/Library/Developer/CommandLineTools/usr/bin/make ship-events-to-s3
kubectl run --rm --attach ship-events \
                --image=amazon/aws-cli:2.4.23 \
                --command=true \
                --restart=Never \
                --env=PGHOST=$(kubectl get secret hive-prod-rds-postgres -o json | jq -r '.data."postgresql-host"'| base64 -d) \
                --env=PGDATABASE=$(kubectl get secret hive-prod-rds-postgres -o json | jq -r '.data."postgresql-database"'| base64 -d) \
                --env=PGUSER=$(kubectl get secret hive-prod-rds-postgres -o json | jq -r '.data."postgresql-username"'| base64 -d) \
                --env=PGPASSWORD=$(kubectl get secret hive-prod-rds-postgres -o json | jq -r '.data."postgresql-password"'| base64 -d) \
                --env=AWS_ACCESS_KEY_ID=$(kubectl get secret sciety-events-shipper-aws-credentials -o json | jq -r '.data."id"'| base64 -d) \
                --env=AWS_SECRET_ACCESS_KEY=$(kubectl get secret sciety-events-shipper-aws-credentials -o json | jq -r '.data."secret"'| base64 -d) \
                -- \
                bash -c 'yum install --assumeyes --quiet postgresql \
                        && psql -c "copy (select json_agg(events) from events) To STDOUT;" > ./events.json \
                        && sed --in-place --expression="s/\\\\n//g" ./events.json \
                        && aws s3 cp "./events.json" "s3://sciety-data-extractions/events.json" \
                '
If you don't see a command prompt, try pressing enter.
upload: ./events.json to s3://sciety-data-extractions/events.json
pod "ship-events" deleted
/Library/Developer/CommandLineTools/usr/bin/make download-events-from-s3
aws s3 cp "s3://sciety-data-extractions/events.json" "./events.json"
download: s3://sciety-data-extractions/events.json to ./events.json
/Library/Developer/CommandLineTools/usr/bin/make .bq-update-events
cat ./events.json \
                | jq -c '.[]' \
                > ./events.jsonl \

cat ./events.jsonl \
                | venv/bin/generate-schema > events.bq-schema.json
Traceback (most recent call last):
  File "/Users/david/work/elife/sciety/data-pipeline/venv/bin/generate-schema", line 5, in <module>
    from bigquery_schema_generator.generate_schema import main
ModuleNotFoundError: No module named 'bigquery_schema_generator'
make[1]: *** [.bq-generate-schema] Error 1
make: *** [.upload-events-from-db-to-bigquery] Error 2
```

**Comment by de-code** [comment]
```
bq load \
        --project_id=elife-data-pipeline \
        --replace \
        --schema=events.bq-schema.json \
        --source_format=NEWLINE_DELIMITED_JSON \
        de_proto.sciety_event_v1 \
        ./events.jsonl
Traceback (most recent call last):
  File "/home/deuser/apps/google-cloud-sdk/platform/bq/bq.py", line 66, in <module>
    import bq_utils
  File "/home/deuser/apps/google-cloud-sdk/platform/bq/bq_utils.py", line 20, in <module>
    import oauth2client_4_0.client
  File "/home/deuser/apps/google-cloud-sdk/platform/bq/third_party/oauth2client_4_0/client.py", line 46, in <module>
    from oauth2client_4_0 import crypt
  File "/home/deuser/apps/google-cloud-sdk/platform/bq/third_party/oauth2client_4_0/crypt.py", line 46, in <module>
    from oauth2client_4_0 import _openssl_crypt
  File "/home/deuser/apps/google-cloud-sdk/platform/bq/third_party/oauth2client_4_0/_openssl_crypt.py", line 17, in <module>
    from OpenSSL import crypto
  File "/home/deuser/apps/google-cloud-sdk/platform/bundledpythonunix/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/deuser/apps/google-cloud-sdk/platform/bundledpythonunix/lib/python3.9/site-packages/OpenSSL/crypto.py", line 3268, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
```

**Comment by giorgiosironi** [comment]
To be able to test the ingress logs export over and over:
```
DELETE
FROM `elife-data-pipeline.de_proto.sciety_ingress_v1`
WHERE PARSE_TIMESTAMP("%d/%b/%Y:%H:%M:%S %z", app_time_local) >= TIMESTAMP("2023-03-19")
```

**Comment by erkannt** [comment]
Target fails on my machine:

```
docker run --volumes-from gcloud-config --volume $PWD/events.bq-schema.json:/events.bq-schema.json:ro --volume $PWD/events.jsonl:/events.jsonl:ro --volume $PWD/data:/data:ro --volume $PWD/logs:/logs:ro --rm google/cloud-sdk:422.0.0-alpine bq load \
        --project_id=elife-data-pipeline \
        --replace \
        --schema=events.bq-schema.json \
        --source_format=NEWLINE_DELIMITED_JSON \
        de_proto.sciety_event_v1 \
        ./events.jsonl
docker: Error response from daemon: No such container: gcloud-config.
See 'docker run --help'.
make[1]: *** [Makefile:76: .bq-update-events] Error 125
make[1]: Leaving directory '/home/hff/work/sciety/data-pipeline'
make: *** [Makefile:87: .upload-events-from-db-to-bigquery] Error 2
```
