### ISSUE TITLE
Allow user details to be updated via the API

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#2196]

**Comment by erkannt** [comment]
Successful update of `avatarUrl` on localhost:

```
curl -v localhost:8080/api/update-user-details -H "Authorization: Bearer secret" -X POST -H "Content-type: application/json" -d '{"id": "991777251543793665", "avatarUrl": "https://pbs.twimg.com/profile_images/1641803935710150657/UCNPqM0G_400x400.jpg"}'
```
```
make dev-sql
SELECT * from events WHERE type='UserDetailsUpdated';
 920ed190-e2ba-47bd-831a-824d7ada60e7 | UserDetailsUpdated | 2023-04-06 08:48:38.726 | {"userId": "twitter|991777251543793665", "avatarUrl": "https://pbs.twimg.com/profile_images/1641803935710150657/UCNPqM0G_400x400.jpg", "displayName": null}
```

**Comment by LinaKind** [comment]
```

> @ start /app
> node ./build/index.js

Unable to start:
{
  "errno": -111,
  "code": "ECONNREFUSED",
  "syscall": "connect",
  "address": "172.23.0.3",
  "port": 5432
}
Error object: {
  "errno": -111,
  "code": "ECONNREFUSED",
  "syscall": "connect",
  "address": "172.23.0.3",
  "port": 5432,
  "name": "Error",
  "message": "connect ECONNREFUSED 172.23.0.3:5432",
  "stack": "Error: connect ECONNREFUSED 172.23.0.3:5432\n    at __node_internal_captureLargerStackTrace (internal/errors.js:412:5)\n    at __node_internal_exceptionWithHostPort (internal/errors.js:590:12)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)"
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node ./build/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-12T14_06_17_008Z-debug.log
```
