### ISSUE TITLE
Collect invalid referers during sign up process

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#2831]

**Comment by LinaKind** [comment]
To reproduce the error:
```
curl -v -H "Referer: abcd" http://localhost:8080/sign-up
```

**Comment by LinaKind** [comment]
Grafana error log:
```
{"timestamp":"2023-11-03T15:12:05.152Z","level":"error","message":"Unhandled Error","payload":{"error":{"message":"Invalid URL","stack":"TypeError [ERR_INVALID_URL]: Invalid URL\n    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)\n    at new NodeError (node:internal/errors:405:5)\n    at new URL (node:internal/url:637:13)\n    at /app/build/http/authentication-destination/calculate-authentication-destination.js:66:16\n    at /app/node_modules/fp-ts/lib/Option.js:210:71\n    at pipe (/app/node_modules/fp-ts/lib/function.js:307:29)\n    at calculateAuthenticationDestination (/app/build/http/authentication-destination/calculate-authentication-destination.js:65:31)\n    at /app/build/http/authentication-destination/authentication-destination.js:207:144\n    at step (/app/build/http/authentication-destination/authentication-destination.js:171:23)\n    at Object.next (/app/build/http/authentication-destination/authentication-destination.js:112:20)\n    at asyncGeneratorStep (/app/build/http/authentication-destination/authentication-destination.js:25:28)\n    at _next (/app/build/http/authentication-destination/authentication-destination.js:43:17)\n    at /app/build/http/authentication-destination/authentication-destination.js:48:13\n    at new Promise (<anonymous>)\n    at /app/build/http/authentication-destination/authentication-destination.js:40:16\n    at /app/build/http/authentication-destination/authentication-destination.js:221:25\n    at dispatch (/app/node_modules/koa-compose/index.js:42:32)\n    at /app/node_modules/@koa/router/lib/router.js:423:16\n    at dispatch (/app/node_modules/koa-compose/index.js:42:32)\n    at /app/node_modules/koa-compose/index.js:34:12\n    at dispatch (/app/node_modules/@koa/router/lib/router.js:428:31)\n    at dispatch (/app/node_modules/koa-compose/index.js:42:32)\n    at /app/node_modules/koa-passport/lib/framework/koa.js:160:16\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async session (/app/node_modules/koa-session/index.js:41:7)"}}}
```
