### ISSUE TITLE
Too many Twitter API requests are being made at runtime

### ISSUE THREAD

**Issue by thewilkybarkid** [sciety/sciety#327]
Introducing Backstop in #326 has revealed rate limits on the Twitter API: [300 user lookups per 15 minutes](https://developer.twitter.com/en/docs/twitter-api/rate-limits). It views the same editorial community page with 29 followers, requesting it 3 viewport sizes * 2 environments, leading to 174 requests. So, running it twice within 15 minutes will break. Also, as the same key is used in prod and staging, they are also affected.

Real traffic to the site would also trigger the problem.

**Comment by thewilkybarkid** [comment]
https://github.com/sciety/sciety/blob/64cc0c3e913c100dee8aff598eb4d939a84ca0af/src/user-page/index.ts#L52

**Comment by giorgiosironi** [comment]
We started getting alerts about this, given the number of errors being in the 50s probably the community page:
```
app_message
Request to Twitter API for user details failed
app_payload.data
Rate limit exceeded
app_payload.error.config.headers.Accept
application/json, text/plain, */*
app_payload.error.config.headers.Authorization
--redacted--
app_payload.error.config.headers.User-Agent
axios/0.19.2
app_payload.error.config.maxContentLength
-1
app_payload.error.config.method
get
app_payload.error.config.timeout
0
app_payload.error.config.url
https://api.twitter.com/2/users/1120053445552214017?user.fields=profile_image_url
app_payload.error.config.xsrfCookieName
XSRF-TOKEN
app_payload.error.config.xsrfHeaderName
X-XSRF-TOKEN
app_payload.error.message
Request failed with status code 429
app_payload.error.name
Error
app_payload.error.stack
Error: Request failed with status code 429
at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:236:11)
at IncomingMessage.emit (events.js:326:22)
at endReadableNT (_stream_readable.js:1252:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by giorgiosironi** [comment]
Also another alert on timeouts, which are more likely with an high number of requests being performed:
```
app_payload.error.config.url
https://api.twitter.com/2/users/--redacted--?user.fields=profile_image_url
app_payload.error.config.xsrfCookieName
XSRF-TOKEN
app_payload.error.config.xsrfHeaderName
X-XSRF-TOKEN
app_payload.error.message
connect ETIMEDOUT 104.244.42.2:443
app_payload.error.name
Error
app_payload.error.stack
Error: connect ETIMEDOUT 104.244.42.2:443
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:129:14)
```
