### ISSUE TITLE
Docmaps index does not load on localhost, produces 500. Figure out why

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#3510]
```
app-1    | {
app-1    |   "timestamp": "2024-09-04T13:34:35.418Z",
app-1    |   "level": "error",
app-1    |   "message": "Error fetching Google sheet",
app-1    |   "payload": {
app-1    |     "error": {
app-1    |       "config": {
app-1    |         "method": "POST",
app-1    |         "url": "https://www.googleapis.com/oauth2/v4/token",
app-1    |         "data": {
app-1    |           "grant_type": "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>.",
app-1    |           "assertion": "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>."
app-1    |         },
app-1    |         "headers": {
app-1    |           "Content-Type": "application/x-www-form-urlencoded",
app-1    |           "User-Agent": "google-api-nodejs-client/9.8.0",
app-1    |           "x-goog-api-client": "gl-node/18.18.2",
app-1    |           "Accept": "application/json"
app-1    |         },
app-1    |         "responseType": "json",
app-1    |         "retryConfig": {
app-1    |           "httpMethodsToRetry": [
app-1    |             "POST"
app-1    |           ],
app-1    |           "currentRetryAttempt": 0,
app-1    |           "retry": 3,
app-1    |           "noResponseRetries": 2,
app-1    |           "statusCodesToRetry": [
app-1    |             [
app-1    |               100,
app-1    |               199
app-1    |             ],
app-1    |             [
app-1    |               408,
app-1    |               408
app-1    |             ],
app-1    |             [
app-1    |               429,
app-1    |               429
app-1    |             ],
app-1    |             [
app-1    |               500,
app-1    |               599
app-1    |             ]
app-1    |           ]
app-1    |         },
app-1    |         "body": "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>."
app-1    |       },
app-1    |       "response": {
app-1    |         "config": {
app-1    |           "method": "POST",
app-1    |           "url": "https://www.googleapis.com/oauth2/v4/token",
app-1    |           "data": {
app-1    |             "grant_type": "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>.",
app-1    |             "assertion": "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>."
app-1    |           },
app-1    |           "headers": {
app-1    |             "Content-Type": "application/x-www-form-urlencoded",
app-1    |             "User-Agent": "google-api-nodejs-client/9.8.0",
app-1    |             "x-goog-api-client": "gl-node/18.18.2",
app-1    |             "Accept": "application/json"
app-1    |           },
app-1    |           "responseType": "json",
app-1    |           "retryConfig": {
app-1    |             "httpMethodsToRetry": [
app-1    |               "POST"
app-1    |             ]
app-1    |           },
app-1    |           "body": "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>."
app-1    |         },
app-1    |         "data": {
app-1    |           "error": "invalid_grant",
app-1    |           "error_description": "Invalid JWT Signature."
app-1    |         },
app-1    |         "headers": {
app-1    |           "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000",
app-1    |           "cache-control": "private",
app-1    |           "connection": "close",
app-1    |           "content-encoding": "gzip",
app-1    |           "content-type": "application/json; charset=UTF-8",
app-1    |           "date": "Wed, 04 Sep 2024 13:34:35 GMT",
app-1    |           "server": "scaffolding on HTTPServer2",
app-1    |           "transfer-encoding": "chunked",
app-1    |           "vary": "Origin, X-Origin, Referer",
app-1    |           "x-content-type-options": "nosniff",
app-1    |           "x-frame-options": "SAMEORIGIN",
app-1    |           "x-xss-protection": "0"
app-1    |         },
app-1    |         "status": 400,
app-1    |         "statusText": "Bad Request",
app-1    |         "request": {
app-1    |           "responseURL": "https://www.googleapis.com/oauth2/v4/token"
app-1    |         }
app-1    |       },
app-1    |       "status": 400,
app-1    |       "name": "Error",
app-1    |       "message": "invalid_grant: Invalid JWT Signature.",
app-1    |       "stack": "Error: invalid_grant: Invalid JWT Signature.\n    at Gaxios._request (/app/node_modules/gaxios/src/gaxios.ts:132:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async GoogleToken._GoogleToken_requestToken (/app/node_modules/gtoken/build/src/index.js:241:19)\n    at async GoogleToken._GoogleToken_getTokenAsync (/app/node_modules/gtoken/build/src/index.js:160:16)\n    at async JWT.refreshTokenNoCache (/app/node_modules/google-auth-library/build/src/auth/jwtclient.js:173:23)\n    at async JWT.getRequestMetadataAsync (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:312:17)\n    at async JWT.requestAsync (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:397:23)"
app-1    |     },
app-1    |     "requestId": "6cbf49d0-6ac2-11ef-96c2-f3f5aaa9b315"
app-1    |   }
app-1    | }
app-1    | {
app-1    |   "timestamp": "2024-09-04T13:34:35.501Z",
app-1    |   "level": "error",
app-1    |   "message": "Error fetching Google sheet",
app-1    |   "payload": {
app-1    |     "error": {
app-1    |       "config": {
app-1    |         "method": "POST",
app-1    |         "url": "https://www.googleapis.com/oauth2/v4/token",
app-1    |         "data": {
app-1    |           "grant_type": "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>.",
app-1    |           "assertion": "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>."
app-1    |         },
app-1    |         "headers": {
app-1    |           "Content-Type": "application/x-www-form-urlencoded",
app-1    |           "User-Agent": "google-api-nodejs-client/9.8.0",
app-1    |           "x-goog-api-client": "gl-node/18.18.2",
app-1    |           "Accept": "application/json"
app-1    |         },
app-1    |         "responseType": "json",
app-1    |         "retryConfig": {
app-1    |           "httpMethodsToRetry": [
app-1    |             "POST"
app-1    |           ],
app-1    |           "currentRetryAttempt": 0,
app-1    |           "retry": 3,
app-1    |           "noResponseRetries": 2,
app-1    |           "statusCodesToRetry": [
app-1    |             [
app-1    |               100,
app-1    |               199
app-1    |             ],
app-1    |             [
app-1    |               408,
app-1    |               408
app-1    |             ],
app-1    |             [
app-1    |               429,
app-1    |               429
app-1    |             ],
app-1    |             [
app-1    |               500,
app-1    |               599
app-1    |             ]
app-1    |           ]
app-1    |         },
app-1    |         "body": "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>."
app-1    |       },
app-1    |       "response": {
app-1    |         "config": {
app-1    |           "method": "POST",
app-1    |           "url": "https://www.googleapis.com/oauth2/v4/token",
app-1    |           "data": {
app-1    |             "grant_type": "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>.",
app-1    |             "assertion": "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>."
app-1    |           },
app-1    |           "headers": {
app-1    |             "Content-Type": "application/x-www-form-urlencoded",
app-1    |             "User-Agent": "google-api-nodejs-client/9.8.0",
app-1    |             "x-goog-api-client": "gl-node/18.18.2",
app-1    |             "Accept": "application/json"
app-1    |           },
app-1    |           "responseType": "json",
app-1    |           "retryConfig": {
app-1    |             "httpMethodsToRetry": [
app-1    |               "POST"
app-1    |             ]
app-1    |           },
app-1    |           "body": "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>."
app-1    |         },
app-1    |         "data": {
app-1    |           "error": "invalid_grant",
app-1    |           "error_description": "Invalid JWT Signature."
app-1    |         },
app-1    |         "headers": {
app-1    |           "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000",
app-1    |           "cache-control": "private",
app-1    |           "connection": "close",
app-1    |           "content-encoding": "gzip",
app-1    |           "content-type": "application/json; charset=UTF-8",
app-1    |           "date": "Wed, 04 Sep 2024 13:34:35 GMT",
app-1    |           "server": "scaffolding on HTTPServer2",
app-1    |           "transfer-encoding": "chunked",
app-1    |           "vary": "Origin, X-Origin, Referer",
app-1    |           "x-content-type-options": "nosniff",
app-1    |           "x-frame-options": "SAMEORIGIN",
app-1    |           "x-xss-protection": "0"
app-1    |         },
app-1    |         "status": 400,
app-1    |         "statusText": "Bad Request",
app-1    |         "request": {
app-1    |           "responseURL": "https://www.googleapis.com/oauth2/v4/token"
app-1    |         }
app-1    |       },
app-1    |       "status": 400,
app-1    |       "name": "Error",
app-1    |       "message": "invalid_grant: Invalid JWT Signature.",
app-1    |       "stack": "Error: invalid_grant: Invalid JWT Signature.\n    at Gaxios._request (/app/node_modules/gaxios/src/gaxios.ts:132:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async GoogleToken._GoogleToken_requestToken (/app/node_modules/gtoken/build/src/index.js:241:19)\n    at async GoogleToken._GoogleToken_getTokenAsync (/app/node_modules/gtoken/build/src/index.js:160:16)\n    at async JWT.refreshTokenNoCache (/app/node_modules/google-auth-library/build/src/auth/jwtclient.js:173:23)\n    at async JWT.getRequestMetadataAsync (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:312:17)\n    at async JWT.requestAsync (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:397:23)"
app-1    |     },
app-1    |     "requestId": "6cbf49d0-6ac2-11ef-96c2-f3f5aaa9b315"
app-1    |   }
app-1    | }
app-1    | {
app-1    |   "timestamp": "2024-09-04T13:34:35.518Z",
app-1    |   "level": "error",
app-1    |   "message": "NCRC evaluation id not found in sheet",
app-1    |   "payload": {
app-1    |     "evaluationUuid": "671d41ca-c8cd-44a3-afd5-c2ebe40a1316",
app-1    |     "requestId": "6cbf49d0-6ac2-11ef-96c2-f3f5aaa9b315"
app-1    |   }
app-1    | }
```

We created a new key at https://console.cloud.google.com/iam-admin/serviceaccounts/details/104048143259449897526/keys?project=sciety

**Comment by giorgiosironi** [comment]
We tried using the key with id `bf9a355e8c68360ac7b4790726a926f9d03b3a4c`, which [is in AWS Secrets Manager](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=ncrc-sheet-google-service-account-key&region=us-east-1) and used by staging and prod. http://localhost:8080/docmaps/v1/articles/10.21203/rs.3.rs-871965/v1.docmap.json loaded correctly.

**Comment by LinaKind** [comment]
Searching for clues with this query:

https://duckduckgo.com/?t=ffab&q=gcp+invalid+jwt+signature&atb=v321-1&ia=web

**Comment by giorgiosironi** [comment]
This is the [Google Sheet](https://docs.google.com/spreadsheets/d/1sMU60q9qvMyvWEH352VvmxSRMZKklWAm_w78mpckzMQ/edit?gid=0#gid=0) providing Sciety with a source of truth for NCRC evaluations. It has been populated by Kotahi until 2021, and it is stable with 398 entries.

The long-term strategy is to replace the Google Sheet integration with Kotahi Docmaps, which will become the source of truth.
